#!/usr/bin/python
import sys
import urllib
import json


data = {
        pred : sys.argv[1],
        obj  : sys.argv[2]
       }

response = urllib.urlopen("http://www.rdfclip.com:8000/api/query",data=json.dumps(data))

print response
